# Problems found: 1
# Run `ameba --only Style/MethodNames` for details
Style/MethodNames:
  Description: Enforces method names to be in underscored case
  Excluded:
  - Geometric/Geometric.cr
  Enabled: true
  Severity: Convention

# Problems found: 2
# Run `ameba --only Lint/ShadowingOuterLocalVar` for details
Lint/ShadowingOuterLocalVar:
  Description: Disallows the usage of the same name as outer local variables for block
    or proc arguments.
  Excluded:
  - test/ImosLinear.test.cr
  Enabled: true
  Severity: Warning

Excluded:
  - atcoder/src/*.cr