[languages.cr]
compile = "crystal build {path} --release -o a.out --error-trace"
execute = "./a.out"
verification_file_suffix = ".test.cr"
bundle = "cr-bundle {path} -f"
list_dependencies = "cr-bundle {path} -d"
