name: api

on: push

jobs:
    api:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: 0.33.0

            - name: Install ac-library
              run: git clone https://github.com/google/ac-library.cr.git atcoder

            - name: Gerarate API docs
              run: |
                  git checkout master
                  crystal docs

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: docs
                  target-folder: api
