name: api

on: push

jobs:
    api:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: 0.33.0

            - name: Set up Python
              uses: actions/setup-python@v1

            - name: Add path
              run: |
                  mkdir bin
                  echo "/home/runner/work/crystal_lib/crystal_lib/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: |
                  sudo apt-get install ruby-full -y
                  pip3 install -U online-judge-verify-helper
                  git clone https://github.com/google/ac-library.cr.git atcoder
                  git clone https://github.com/yuruhi/cr-bundle.git
                  crystal build cr-bundle/src/cli.cr -o bin/cr-bundle
                  rm -rf cr-bundle

            - name: Generate API docs
              run: |
                  git checkout master
                  crystal docs -o dist/api

            - name: Generate bundled docs
              run: |
                  oj-verify docs --jobs 4
                  sudo gem install bundler
                  sudo bundle install --gemfile=.verify-helper/markdown/Gemfile --path .vendor/bundle
                  bundle exec --gemfile=.verify-helper/markdown/Gemfile jekyll build --source .verify-helper/markdown --destination dist/docs --baseurl crystal_lib/docs

            - name: Deploy docs to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
