name: api

on: push

jobs:
    api:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: 0.33.0

            - name: Set up Python
              uses: actions/setup-python@v1

            - name: Install dependencies
              run: |
                  sudo apt-get install ruby-full -y
                  pip3 install -U online-judge-verify-helper
                  git clone https://github.com/google/ac-library.cr.git atcoder

            - name: Generate API docs
              run: |
                  git checkout master
                  crystal docs -o dist/api

            - name: Generate bundled docs
              run: |
                  git oj-verify docs --jobs 4
                  gem install bundler
                  bundle install --gemfile=.verify-helper/markdown/Gemfile --path .vendor/bundle
                  bundle exec --gemfile=.verify-helper/markdown/Gemfile jekyll build --source .verify-helper/markdown --destination dist/docs --baseurl ac-library.cr/docs

            - name: Deploy docs to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
