name: linter

on: push

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: latest

            - name: Run format check
              run: crystal tool format --check --exclude atcoder

            - name: Install Ameba
              run: shards install

            - name: Run linter
              run: bin/ameba
