name: verify

on: push

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: 0.33.0

            - name: Add path
              run: |
                  mkdir bin
                  echo "/home/runner/work/crystal_lib/crystal_lib/bin" >> $GITHUB_PATH

            - name: Install latest Crystal
              run: |
                  wget https://github.com/crystal-lang/crystal/releases/download/1.0.0/crystal-1.0.0-1-linux-x86_64.tar.gz
                  tar xf crystal-1.0.0-1-linux-x86_64.tar.gz
                  cp crystal-1.0.0-1/bin/crystal bin/crystal-latest

            - name: Install dependencies
              run: pip3 install -U online-judge-verify-helper

            - name: Install cr-bundle
              run: |
                  git clone https://github.com/yuruhi/cr-bundle.git
                  crystal build cr-bundle/src/cli.cr -o bin/cr-bundle --release
                  rm -rf cr-bundle

            - name: Install Ameba
              run: |
                  git clone https://github.com/crystal-ameba/ameba
                  crystal-latest build ameba/src/cli.cr -o bin/ameba --release
                  rm -rf ameba

            - name: Install ac-library
              run: git clone https://github.com/google/ac-library.cr.git atcoder

            - name: Run format check
              run: crystal tool format --check {datastructure,DP,graph,math,spec,template,utility,Geometric,string,test}/

            - name: Run spec
              run: crystal spec

            - name: Run Ameba
              run: ameba

            - name: Run tests
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
                  GH_PAT: ${{ secrets.GH_PAT }}
              # run: oj-verify run --jobs 4
              run: oj-verify run test/bfs.test.cr

            - name: Gerarate API docs
              run: |
                  git checkout master
                  crystal docs ./{datastructure,DP,Geometric,graph,math,string,template,utility}/*

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: docs
                  target-folder: api
