name: verify

on: push

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: 0.33.0

            - name: Add path
              run: |
                  mkdir bin
                  echo "/home/runner/work/crystal_lib/crystal_lib/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: pip3 install -U online-judge-verify-helper

            - name: Install cr-bundle
              run: |
                  git clone https://github.com/yuruhi/cr-bundle.git
                  crystal build cr-bundle/src/cli.cr -o bin/cr-bundle
                  rm -rf cr-bundle

            - name: Install ac-library
              run: git clone https://github.com/google/ac-library.cr.git atcoder

            - name: Run format check
              run: crystal tool format --check --exclude atcoder

            - name: Run spec
              run: crystal spec

            - name: Run tests
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
                  GH_PAT: ${{ secrets.GH_PAT }}
              # run: oj-verify run --jobs 4
              run: |
                  git checkout master
                  oj-verify run test/graph/bfs.test.cr
