name: verify

on: push

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up Python
              uses: actions/setup-python@v1

            - name: Set up Crystal
              uses: oprypin/install-crystal@v1
              with:
                  crystal: 0.33.0

            - name: Add path
              run: mkdir bin && echo `pwd`/bin >> $GITHUB_PATH

            - name: Install dependencies
              run: |
                  pip3 install -U online-judge-verify-helper
                  sudo apt-get install ruby-full -y
                  sudo gem install bundler

            - name: Install ac-library
              run: |
                  git clone https://github.com/google/ac-library.cr.git atcoder
                  rm atcoder/{benchmarks,spec,verify}/*

            # - name: Run spec
            # run: crystal spec

            - name: Install cr-bundle
              run: |
                  git clone https://github.com/yuruhi/cr-bundle.git
                  crystal build cr-bundle/src/cli.cr -o bin/cr-bundle
                  rm -rf cr-bundle

            - name: Run tests
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
                  GH_PAT: ${{ secrets.GH_PAT }}
              run: oj-verify all --jobs 4

            - name: Checkout
              run: |
                  git checkout master
                  rm -rf atcoder
                  git clone https://github.com/google/ac-library.cr.git atcoder
                  rm atcoder/{benchmarks,spec,verify}/*
                  git clone https://github.com/yuruhi/cr-bundle.git
                  crystal build cr-bundle/src/cli.cr -o bin/cr-bundle
                  rm -rf cr-bundle

            - name: Generate API docs
              run: crystal docs -o dist/api

            - name: Generate bundled docs
              run: |
                  oj-verify docs
                  sudo bundle install --gemfile=.verify-helper/markdown/Gemfile --path .vendor/bundle
                  bundle exec --gemfile=.verify-helper/markdown/Gemfile jekyll build --source .verify-helper/markdown --destination dist/docs --baseurl crystal_lib/docs

            - name: Deploy docs to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
